### ISSUE TITLE
Feature request: add import ability

### ISSUE THREAD

**Issue by THEshezzee** [LordMZTE/mcstat#1]
Import host addresses  by file format `host:port`
Example usage: `./mcstat -i host.txt`

**Comment by LordMZTE** [comment]
Not quite sure what you mean by "import". If you want to ping all servers in a file, you can use some basic shell scripting for that:
```bash
while read server; do
    mcstat $server
done < servers.txt
```

**Comment by THEshezzee** [comment]
Wow, thx! Its works! Big thanks
